### ISSUE TITLE
Properties not validated when their schema is referenced indirectly within an anyOf or oneOf

### ISSUE THREAD

**Issue by thetumper** [swagger-model-validator/swagger-model-validator#118] opened 2019-11-05 03:36 UTC
Validation is not performed on properties that are referenced indirectly within an anyOf or oneOf structure.  For example, given an AddressType schema like this:

            AddressType: {
              type: 'object',
              properties: {
                line1: {
                  type: 'string',
                  description: 'Address line 1',
                  example: '300 E Main St',
                },
                line2: {
                  type: 'string',
                  description: 'Address line 2',
                  example: 'Apt. 14',
                },
                city: {
                  type: 'string',
                  description: "City, e.g. 'Madison'",
                },
                stateCode: {
                  type: 'string',
                  description: 'State code',
                  example: 'WI',
                  pattern: '^([A-Z]{2})$',
                },
                zip5: {
                  type: 'string',
                  description: '5-digit ZIP code',
                  example: '53780',
                  pattern: '^([0-9]{5})$',
                },
              },
              required: ['line1', 'city', 'stateCode', 'zip5'],
            },

The pattern on stateCode or zip5 is enforced as expected when AddressType is referenced directly.  E.g.:

            Person: {
              type: 'object',
              properties: {
                address: {
                  $ref: '#/components/schemas/AddressType',
                },
                name: {
                  $ref: '#/components/schemas/Name',
                },
              },
              required: ['address', 'name'],
            },

But, the pattern on stateCode or zip5 is not enforced when the AddressType schema is referenced indirectly.  E.g.:

            Person: {
              type: 'object',
              properties: {
                contactMechanism: {
                  $ref: '#/components/schemas/ContactMechanisms',
                },
                name: {
                  $ref: '#/components/schemas/Name',
                },
              },
              required: ['contactMechanism', 'name'],
            },

            ContactMechanisms: {
              type: 'object',
              oneOf: [{$ref: '#/components/schemas/AddressType'}, {$ref: '#/components/schemas/PhoneType'}],
            },

Expected:  the validity of AddressType properties should be ascertained and enforced regardless of the nestedness or conditionality within the structure, when the schema comes into play in actuality.

Added a test in a forked repo to demonstrate a failing scenario:
https://github.com/thetumper/swagger-model-validator

**Comment by thetumper** [comment] 2019-11-05 18:12
Added a test illustrating the problem here:

https://github.com/thetumper/swagger-model-validator

**Comment by brodyd** [comment] 2019-11-15 03:41
oneOf validation does not appear to support objects (only native types - like string, integer).  I'm investigating extending support to objects as well.

It also appears that the oneOf keyword should not have a type associated with the property.

    ContactMechanisms: {
      oneOf: [
        {$ref: '#/components/schemas/AddressType'}, 
        {$ref: '#/components/schemas/PhoneType'}]
    },

**Comment by brodyd** [comment] 2019-12-11 20:25
I've added correct processing of the oneOf keyword for objects.  It will be deployed in 3.0.12

**Comment by YouvaB** [comment] 2019-12-17 14:52
```js
var errorResult = validateType(name, value, oneOfArray[x], models, allowBlankTargets, disallowExtraProperties);
console.log('Error Result',errorResult)
if(errorResult===null) {
       return null;
}
var error = new Error(name + " is not a valid target for a oneOf");
error.errors = errorResult;
errors.push(new Error(error));
console.log('Errors Array', errors)
```
This piece of code isn't working as intended.

This is the error I should be getting
```
Error Result {
  valid: false,
  errorCount: 1,
  errors: [
    Error: Target property '_class' is not in the model
        at validateProperties (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:182:29)
        at validateSpecification (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:217:22)
        at validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:106:26)
        at validateType (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:310:20)
        at validateValue (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:269:23)
        at validateSpecification (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:243:39)
        at validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:106:26)
        at C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:471:31
        at Array.forEach (<anonymous>)
        at validateArray (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:470:19)
        at validateType (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:378:16)
        at validateValue (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:269:23)
        at validateSpecification (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:243:39)
        at validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:106:26)
        at validateType (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:310:20)
        at validateType (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:321:35)
        at validateValue (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:269:23)
        at validateSpecification (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:243:39)
        at validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:106:26)
        at Object.Validator.swagger.validateModel (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:46:20)
        at OpenApiInputValidator.validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\src\utils\OpenApiInputValidator.ts:16:37)
        at ReceiptBatchController.postReceiptBatches (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\src\controllers\ReceiptBatchController.ts:66:45)
  ],
  GetErrorMessages: [Function],
  GetFormattedErrors: [Function],
  modelName: 'incomeSummary'
}
```

And this is what I get as an error:

```
Errors Array [
  Error: Error: incomeSummary is not a valid target for a oneOf
      at validateType (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:328:29)
      at validateValue (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:269:23)
      at validateSpecification (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:243:39)
      at validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:106:26)
      at Object.Validator.swagger.validateModel (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\swagger-model-validator\lib\modelValidator.js:46:20)
      at OpenApiInputValidator.validate (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\src\utils\OpenApiInputValidator.ts:16:37)
      at ReceiptBatchController.postReceiptBatches (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\src\controllers\ReceiptBatchController.ts:66:45)
      at C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\src\core\app.ts:392:13
      at Layer.handle [as handle_request] (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\route.js:112:3)
      at Layer.handle [as handle_request] (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\index.js:275:10)
      at cors (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\cors\lib\index.js:188:7)
      at C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\cors\lib\index.js:224:17
      at originCallback (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\cors\lib\index.js:214:15)
      at C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\cors\lib\index.js:219:13
      at optionsCallback (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\cors\lib\index.js:199:9)
      at corsMiddleware (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\cors\lib\index.js:204:7)
      at Layer.handle [as handle_request] (C:\Users\uboumyo\Desktop\Projets\RDE\cashing\fin-cashing-deposit-api\node_modules\express\lib\router\layer.js:95:5)
]
```

Hopefully this helps.

**Comment by brodyd** [comment] 2019-12-24 07:16
Your fix has been taken in.  I'll push that out in the new year.  Thanks

**Comment by YouvaB** [comment] 2019-12-24 16:09
My pleasure! Happy holidays!

**Comment by brodyd** [comment] 2020-01-07 01:34
Released

**Closed by brodyd** 2020-01-07 01:34 UTC
Labels: MissingValidation, OpenApi3.0, bug
